/*
 * Automatically generated C config: don't edit
 */
/*
 * Version Number
 */
#ifndef LOSCFG_MODULE_SWITCH
#define LOSCFG_MODULE_SWITCH

/*
 * Compiler
 */
#undef LOSCFG_COMPILER_LITEOS_32
#define LOSCFG_COMPILER_HIMIX100_32 1
#undef LOSCFG_COMPILER_HIMIX200_32
#undef LOSCFG_COMPILER_HIMIX100_64
#undef LOSCFG_COMPILER_CORTEX_M7

/*
 * Platform
 */
#undef LOSCFG_PLATFORM_HI3516A
#undef LOSCFG_PLATFORM_HI3518EV200
#undef LOSCFG_PLATFORM_HI3519
#undef LOSCFG_PLATFORM_HI3519V101
#undef LOSCFG_PLATFORM_HI3559
#undef LOSCFG_PLATFORM_HI3911
#undef LOSCFG_PLATFORM_HIM5V100
#undef LOSCFG_PLATFORM_HI3516CV300
#undef LOSCFG_PLATFORM_HI3731
#undef LOSCFG_PLATFORM_HI3559AV100ES
#undef LOSCFG_PLATFORM_HI3559AV100
#undef LOSCFG_PLATFORM_HI3556AV100
#undef LOSCFG_PLATFORM_HI3519AV100
#undef LOSCFG_PLATFORM_HI3516CV500
#undef LOSCFG_PLATFORM_HI3516EV200
#undef LOSCFG_PLATFORM_HI3516DV300
#undef LOSCFG_PLATFORM_HI3556V200
#define LOSCFG_PLATFORM_HI3559V200 1
#undef LOSCFG_ARCH_ARM926
#undef LOSCFG_ARCH_CORTEX_M7
#define LOSCFG_ARCH_CORTEX_A7 1
#undef LOSCFG_ARCH_CORTEX_A17
#undef LOSCFG_ARCH_CORTEX_A53_AARCH32
#undef LOSCFG_ARCH_CORTEX_A53_AARCH64
#define LOSCFG_PLATFORM_HISI_AMP 1

/*
 * Kernel
 */
#define LOSCFG_KERNEL_LITEKERNEL 1
#undef LOSCFG_KERNEL_MEM_TLSF
#define LOSCFG_KERNEL_EXTKERNEL 1
#define LOSCFG_KERNEL_CPPSUPPORT 1
#undef LOSCFG_KERNEL_MPU
#define LOSCFG_KERNEL_CPUP 1
#define LOSCFG_CPUP_INCLUDE_IRQ 1
#define LOSCFG_KERNEL_DYNLOAD 1
#undef LOSCFG_KERNEL_RUNSTOP
#undef LOSCFG_KERNEL_SCATTER
#undef LOSCFG_KERNEL_TICKLESS

/*
 * Lib
 */
#define LOSCFG_LIB_LIBC 1
#undef LOSCFG_LIB_LIBCMINI
#define LOSCFG_LIB_LIBM 1
#define LOSCFG_LIB_ZLIB 1

/*
 * Compat
 */
#undef LOSCFG_COMPAT_CMSIS
#define LOSCFG_COMPAT_POSIX 1
#define LOSCFG_COMPAT_LINUX 1

/*
 * FileSystem
 */
#define LOSCFG_FS_VFS 1
#undef LOSCFG_FS_FAT
#undef LOSCFG_FS_RAMFS
#undef LOSCFG_FS_ROMFS
#undef LOSCFG_FS_YAFFS
#define LOSCFG_FS_PROC 1
#undef LOSCFG_FS_JFFS

/*
 * Net
 */
#undef LOSCFG_NET_LWIP_SACK

/*
 * Debug
 */
#undef LOSCFG_COMPILE_DEBUG
#define LOSCFG_PLATFORM_ADAPT 1
#undef LOSCFG_COREDUMP
#undef LOSCFG_GDB
#undef LOSCFG_THUMB
#undef LOSCFG_PLATFORM_DVFS
#define LOSCFG_DEBUG_VERSION 1
#define LOSCFG_SHELL 1
#undef LOSCFG_SHELL_LK
#define LOSCFG_SHELL_DMESG 1
#undef LOSCFG_SHELL_EXCINFO
#undef LOSCFG_TOOLS_IPERF
#undef LOSCFG_EXC_INTERACTION
#undef LOSCFG_MEM_MUL_MODULE
#undef LOSCFG_MEM_MUL_POOL
#undef LOSCFG_MEM_HEAD_BACKUP
#undef LOSCFG_MEM_RECORDINFO
#undef LOSCFG_BASE_MEM_NODE_INTEGRITY_CHECK
#undef LOSCFG_BASE_MEM_NODE_SIZE_CHECK
#define LOSCFG_DRIVERS_UART 1
#undef LOSCFG_PLATFORM_UART_WITHOUT_VFS
#define LOSCFG_PLATFORM_OSAPPINIT 1
#undef LOSCFG_TEST
#undef LOSCFG_LLTREPORT

/*
 * Driver
 */
#define LOSCFG_DRIVERS 1
#define LOSCFG_DRIVERS_BASE 1
#undef LOSCFG_DRIVERS_CPUFREQ
#undef LOSCFG_DRIVERS_DEVFREQ
#undef LOSCFG_DRIVERS_REGULATOR
#define LOSCFG_DRIVERS_GPIO 1
#undef LOSCFG_DRIVERS_HIDMAC
#define LOSCFG_DRIVERS_I2C 1
#define LOSCFG_I2C_ADAPTER_COUNT 5
#define LOSCFG_HOST_TYPE_HIBVT 1
#define LOSCFG_DRIVERS_MEM 1
#undef LOSCFG_DRIVERS_MMC
#undef LOSCFG_DRIVERS_MTD
#define LOSCFG_DRIVERS_RANDOM 1
#define LOSCFG_DRIVERS_RTC 1
#define LOSCFG_DRIVERS_SPI 1
#undef LOSCFG_DRIVERS_USB
#define LOSCFG_DRIVERS_VIDEO 1

/*
 * Stack Smashing Protector (SSP) Compiler Feature
 */
#undef LOSCFG_CC_NO_STACKPROTECTOR
#define LOSCFG_CC_STACKPROTECTOR 1
#undef LOSCFG_CC_STACKPROTECTOR_ALL

#endif
