/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2018-2019. All rights reserved.
 *
 * @file    msg_vproc.h
 * @brief   msg vproc header
 * @author  HiMobileCam NDK develop team
 * @date  2019-3-26
 */
#ifndef __MSG_SERVER_VPROC_H__
#define __MSG_SERVER_VPROC_H__

typedef enum hiMSG_VPROC_CMD_E {
    MSG_CMD_VPROC_INIT_VPSS = 0,
    MSG_CMD_VPROC_DEINIT_VPSS,

    MSG_CMD_VPROC_BIND_VCAP,
    MSG_CMD_VPROC_UNBIND_VCAP,

    MSG_CMD_VPROC_SET_VPORT_ATTR,
    MSG_CMD_VPROC_GET_VPORT_ATTR,

    MSG_CMD_VPROC_START_VPORT,
    MSG_CMD_VPROC_STOP_VPORT,

    MSG_CMD_VPROC_SET_VPORT_ATTREX,
    MSG_CMD_VPROC_GET_VPORT_ATTREX,

    MSG_CMD_VPROC_CREAT_STITCH,
    MSG_CMD_VPROC_DESTROY_STITCH,

    MSG_CMD_VPROC_SET_STITCH_ATTR,
    MSG_CMD_VPROC_GET_STITCH_ATTR,

    MSG_CMD_VPROC_SET_STITCH_PORT_ATTR,
    MSG_CMD_VPROC_GET_STITCH_PORT_ATTR,

    MSG_CMD_VPROC_START_STITCH_PORT,
    MSG_CMD_VPROC_STOP_STITCH_PORT,

    MSG_CMD_VPROC_INIT_PHOTO,
    MSG_CMD_VPROC_DEINIT_PHOTO,
    MSG_CMD_VPROC_PHOTO_PROCESS,
    /* photo process dump BNRRaw and YUV */
    MSG_CMD_VPROC_PHOTO_PROCESS_GETBNR,
    MSG_CMD_VPROC_PHOTO_PROCESS_GETYUV,
    MSG_CMD_VPROC_PHOTO_PROCESS_ALGPROCESS,
    MSG_CMD_VPROC_PHOTO_PROCESS_SEND,
    MSG_CMD_VPROC_GET_CURRENT_PHOTO_TYPE,
    MSG_CMD_VPROC_SET_PHOTO_ALGCOEF,
    MSG_CMD_VPROC_GET_PHOTO_ALGCOEF,

    MSG_CMD_VPROC_GET_CHN_FRAME,
    MSG_CMD_VPROC_RELEASE_CHN_FRAME,

    MSG_CMD_VPROC_SET_DUMP_YUV_ATTR,
    MSG_CMD_VPROC_GET_DUMP_YUV_ATTR,

    MSG_CMD_VPROC_SET_OSD_ATTR,
    MSG_CMD_VPROC_GET_OSD_ATTR,
    MSG_CMD_VPROC_START_OSD,
    MSG_CMD_VPROC_STOP_OSD,
} MSG_VPROC_CMD_E;

#endif /* __MSG_SERVER_VPROC_H__ */
