/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2018-2019. All rights reserved.
 *
 * @file    msg_vcap.h
 * @brief   msg vcap header
 * @author  HiMobileCam NDK develop team
 * @date  2019-3-26
 */
#ifndef __MSG_SERVER_VCAP_H__
#define __MSG_SERVER_VCAP_H__

typedef enum tagMSG_VCAP_CMD_E {
    MSG_CMD_SENSOR_INIT = 0,
    MSG_CMD_SENSOR_DEINIT,
    MSG_CMD_SENSOR_GETATTR,
    MSG_CMD_SENSOR_SET_FRAMERATE,
    MSG_CMD_SENSOR_GET_FRAMERATE,
    MSG_CMD_SENSOR_GET_MODESCNT,
    MSG_CMD_SENSOR_GET_ALLMODES,
    MSG_CMD_VCAP_SET_ATTR,
    MSG_CMD_VCAP_GET_ATTR,
    MSG_CMD_VCAP_START_DEV,
    MSG_CMD_VCAP_STOP_DEV,
    MSG_CMD_VCAP_START_CHN,
    MSG_CMD_VCAP_STOP_CHN,
    MSG_CMD_VCAP_START_ISP,
    MSG_CMD_VCAP_STOP_ISP,
    MSG_CMD_VCAP_SET_SNAPATTR,
    MSG_CMD_VCAP_GET_SNAPATTR,
    MSG_CMD_VCAP_SET_SNAPATTR_EX,
    MSG_CMD_VCAP_GET_SNAPATTR_EX,
    MSG_CMD_VCAP_START_TRIGGER,
    MSG_CMD_VCAP_STOP_TRIGGER,
    MSG_CMD_VCAP_SET_STITCHATTR,
    MSG_CMD_VCAP_GET_STITCHATTR,
    MSG_CMD_VCAP_STITCH_TRIGGER,
    MSG_CMD_VCAP_SET_ATTR_EX,
    MSG_CMD_VCAP_GET_ATTR_EX,
    MSG_CMD_VCAP_SET_CROPATTR,
    MSG_CMD_VCAP_GET_CROPATTR,
    MSG_CMD_VCAP_SETEXIF,
    MSG_CMD_VCAP_GETEXIF,
    MSG_CMD_VCAP_SETOSDATTR,
    MSG_CMD_VCAP_GETOSDATTR,
    MSG_CMD_VCAP_START_OSD,
    MSG_CMD_VCAP_STOP_OSD,
    MSG_CMD_VCAP_SET_DISATTR,
    MSG_CMD_VCAP_GET_DISATTR,
    MSG_CMD_VCAP_SET_DUMP_RAW,
    MSG_CMD_VCAP_GET_DUMP_RAW,
    MSG_CMD_VCAP_START_DUMP_RAW,
    MSG_CMD_VCAP_GET_RAWFRAME,
    MSG_CMD_VCAP_RELEASE_RAWFRAME,
    MSG_CMD_VCAP_SET_DUMP_BNRRAW,
    MSG_CMD_VCAP_GET_DUMP_BNRRAW,
    MSG_CMD_VCAP_START_DUMP_BNRRAW,
    MSG_CMD_VCAP_STOP_DUMP_BNRRAW,
    MSG_CMD_VCAP_INIT_MOTIONSENSOR,
    MSG_CMD_VCAP_DEINIT_MOTIONSENSOR,
    MSG_CMD_VCAP_AHD_GET_STATUS,
    MSG_CMD_VCAP_AHD_CHANGE_CHN,

    MSG_CMD_VCAP_BUTT
} MSG_VCAP_CMD_E;

#endif /* __MSG_SERVER_VCAP_H__ */
