#!/bin/sh

# mount appfs
#sleep 0.1
#mount -t jffs2 /dev/mtdblock6 /app
#mount -t yaffs /dev/mtdblock6 /app
#ubiattach /dev/ubi_ctrl -m 6
#mount -t ubifs ubi1:ubifs /app

#start application
cd /app
./bootapp
